### ISSUE TITLE
undefined local variable or method `page_title' 

### ISSUE THREAD

**Issue by rtacconi** [rbriank/refinerycms_membership#28]
since the latest branch is not working with refinery 1.0.8 I am using the previous one. But I get this 

undefined local variable or method `page_title' for #<#Class:0x0000010894b778:0x00000108948438>
